### ISSUE TITLE
Can't share content in Safari browser.

### ISSUE THREAD

**Issue by iamytg** [aws/amazon-chime-sdk-component-library-react#607] opened 2021-09-07 10:33 UTC
### What happened and what did you expect to happen?

A attendee using the Safari browser shared the content, and the shared content was visible in their featured video area, but not visible to other attendees. The featured video area was expanded to other attendees, but nothing was shown in the video.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [x] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Create any one meeting room.
2. Invite 3 attendees to the meeting room. At least one person uses the Safari browser.
3. Bring two or more attendees into the meeting room. At least one person uses the Safari browser.
4. One of the Safari browser attendees shares content.
5. The rest of the attendees cannot see the shared content video.

### Amazon Chime SDK React Components Library version

2.9.1

### What browsers are you seeing the problem on?

Safari

### Browser version

14.1.2

### Device Information

macOS Big Sur 11.5.2(20G95), MacBook Air (M1, 2020)

### Meeting and Attendee ID Information.

meeting_id: "a637162e-9c3a-4cf1-9001-8e84a6fc0706"
chimeAttendeeId: "dfe03546-50f1-4877-864e-455cc00a13d2"

### Browser console logs

[Log] [MeetingManager audioVideoDidStart] Meeting started successfully (2.8d4c936a.chunk.js, line 2)
[Warning] 2021-09-07T10:28:30.792Z [WARN] SDK - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false (2.8d4c936a.chunk.js, line 2)
[Warning] 2021-09-07T10:28:30.795Z [WARN] SDK - will retry due to status code ConnectionHealthReconnect (2.8d4c936a.chunk.js, line 2)
[Warning] 2021-09-07T10:28:30.803Z [WARN] SDK - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false (2.8d4c936a.chunk.js, line 2)
[Warning] 2021-09-07T10:29:20.791Z [WARN] SDK - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false (2.8d4c936a.chunk.js, line 2)
[Warning] 2021-09-07T10:29:20.792Z [WARN] SDK - will retry due to status code ConnectionHealthReconnect (2.8d4c936a.chunk.js, line 2)

### Add any other context about the problem here.

When you start sharing content in Safari browser, like Chrome or Firefox, a dialog to select a screen, window, or tab does not appear, but the current screen is selected and content sharing starts.

**Comment by ldai1** [comment] 2021-09-08 07:06
Tested on M1 device with MacOS Big Sur 11.4 and Safari 14.1.1, was able to reproduce the issue. The safari attendee is able to choose a screen and share the content but other attendees are not able to see any content. The issue is not reproducible on Mac intel devices.

**Comment by ldai1** [comment] 2021-09-09 01:27
Found that in Safari, there is no screen sharing setting for Chime meetings.
Reproduce step:
1. Click Safari > Settings for this website
2. Check that the Screen Sharing field.

For chime meeting, there is no Screen Sharing field.

**Comment by xuesichao** [comment] 2021-11-15 18:51
The React Component Library is built on top of [Amazon Chime JS SDK](https://github.com/aws/amazon-chime-sdk-js).
This issue is tracked here: https://github.com/aws/amazon-chime-sdk-js/issues/1209
Close it due to duplication.

**Closed by xuesichao** 2021-11-15 18:51 UTC
Labels: Browser Bug
