### ISSUE TITLE
Support React 18 + TypeScript

### ISSUE THREAD

**Issue by kelvin-thinkbean** [aws/amazon-chime-sdk-component-library-react#786] opened 2022-04-14 07:55 UTC
### What happened and what did you expect to happen?

After upgrading to React 18 in my Typescript project, I experienced several type related issues. This is because of the decision of the React team to [remove implicit children](https://solverfox.dev/writing/no-implicit-children/) (see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210).

There is a [codemode](https://github.com/eps1lon/types-react-codemod) provided which basically wraps all the props with `React.PropsWithChildren<YourProps>` which could come in handy for you.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

- [Upgrade to React 18](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode) in a TypeScript project
- Notice how the MeetingProvider (and several other elements) have type issues related to the React team's decision to [remove implicit children](https://solverfox.dev/writing/no-implicit-children/) from the FC type.

### Amazon Chime SDK React Components Library version

3.0.0

### What browsers are you seeing the problem on?

N/A

### Browser version

N/A

### Device Information

N/A

### Browser console logs

N/A

**Comment by devalevenkatesh** [comment] 2022-04-18 20:28
Thanks for reporting this issue. We will provide more updates as we make progress. But for now we are tracking this internally.

**Comment by everscending** [comment] 2022-10-24 12:27
@kelvin-thinkbean amazon-chime-sdk-component-library-react  peer dependencies include  react v17.  Did you use --force or --legacy-peer-deps to get react v18 installed?

**Comment by beefancohen** [comment] 2022-10-27 20:49
@devalevenkatesh are there immediate plans for upgrading the peer dep? it is blocking us from upgrading.  thanks for a great lib!

**Comment by devalevenkatesh** [comment] 2022-10-27 20:53
Hi @beefancohen ,

Thank you for trying out the library. Unfortunately, I am sad to tell we have not yet prioritized due to other priorities. I will keep this issue updated once we have an update. Thanks again!

**Comment by beefancohen** [comment] 2022-10-27 20:54
@devalevenkatesh thank you! would you accept a PR perhaps?

**Comment by devalevenkatesh** [comment] 2022-10-27 21:01
Yes, definitely would like that. Though, there are multiple problem with React 18 upgrade for us and time consuming to fix. Below are the things we need to update in order:
1. Storybook's `@storybook/addon-knob` is deprecated now and uses react 17, hence we have to move to use `@storybook/addon-controls`.
2. `react-popper` and `@popper/code-js` need to be updated to `2.7.0`. Check and test if `PopOver` or related components function properly which use `react-popper`.
3. Update `react`, `react-dom`, `@types/react`, `@types/react-dom` to `^18.0.0` version.
4. `children` should now be added as an explicit prop on all components using or rendering `children` elements.
5. Also, not sure, but there are changes to `useEffect` cycle as well so have to test each and every component from that standpoint.

We did some progress and realized there're more than 70+ *.stories.tsx of UI Components need to be migrated from @storybook/addon-knob to @storybook/addon-controls.

Example: https://github.com/aws/amazon-chime-sdk-component-library-react/commit/ec959964af0cbfba7729ba294657c909e3f60d4f

**Comment by beefancohen** [comment] 2022-10-27 21:10
awesome ty... posting the migration instructions for storybook here for posterity: https://github.com/storybookjs/storybook/blob/next/code/addons/controls/README.md#how-do-i-migrate-from-addon-knobs

**Comment by xuesichao** [comment] 2022-10-27 21:22
The major issue for migrate to `@storybook/addon-controls` is that we need to update all our stories to `arg` based, the auto-generated args doesn't work well for our stories, so we have to manually do that.

**Comment by iquirino** [comment] 2022-10-31 23:04
+1

**Comment by Robertorc83** [comment] 2022-11-07 13:04
Still having the same problem with the last update (3.4.0), is there any workaround for this?

**Comment by osamabinsaleem** [comment] 2022-11-08 10:29
with react 17, I'm getting this issue with ```MeetingProvider```. 

`Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & Props'.ts(2559)`

**Comment by devalevenkatesh** [comment] 2022-11-08 16:29
Thanks for reporting @Robertorc83 and @osamabinsaleem . This is not a bug with the library rather React 18 is not supported yet with `amazon-chime-sdk-component-library-react`. Unfortunately we do not have a time frame to report on the progress yet, please check [previous](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/786#issuecomment-1294057786) comment for more details.

**Comment by dmoughabghab** [comment] 2022-11-16 10:22
+1 Please. Is there any timeframe as of yet?

**Comment by woohelps** [comment] 2022-11-17 21:34
+1 Please. Is there any timeframe as of yet?

**Comment by dmoughabghab** [comment] 2022-11-23 22:20
I made a version where I got rid of story book altogether and did all the adding children prop to components work and it builds successfully, do you want me to commit a branch where items 2, 3 and 4 are done?

**Comment by gvnavin** [comment] 2022-12-22 18:02
+1

 have been facing some issue in chime front end integration, and I am trying to use any tag from Amazon chime SDK component library react getting error.

 
Example tag : <VideoTile nameplate="Test name"/>

Chime version : "amazon-chime-sdk-component-library-react": "^3.4.0",  "amazon-chime-sdk-js": "^3.9.0"

dependencies version : 
"react": "^18.2.0",        
"react-dom": "^18.2.0",            
"react-router": "^6.3.0",  
"react-router-dom": "^6.3.0",

**Comment by gvnavin** [comment] 2023-01-24 08:19
We built all our front end app using react 18. Since chime is not supported in react 18, we need to do lot of work around like creating a separate react app to compile down it to simple js code and include them in main app inside iframe. It caused lot of churn and delayed the project deliverables.  We think that it is going to cause continuous maintanence issues.

I would request the team to prioritize this issue and upgrade the library.

Thank you.

**Comment by flozero** [comment] 2023-03-20 20:58
I am actually working on the react 18 implementation. Is it still something people need ?   If yes as Its a ton of time consuming.
Would you consider participating financially for the project that will implement it or is it something people will except to use freely ?

**Comment by flozero** [comment] 2023-03-21 19:55
Just so you know. I have started a react 18 implementation of it. If you want to read more and support the project please take time to star the project or support via github sponsor. I will make sure to keep the readme updated

https://github.com/flozero/react-18-chime-js-sdk

**Comment by flozero** [comment] 2023-03-28 20:15
@Amethystix I have migrate everything into react 18 syntax here https://github.com/flozero/react-18-chime-js-sdk

You can install the package react-18-chime-js-sdk. I am finishing integrating this in my personal project and will offer this project to take backt he ownership if someone end up answering :)

**Comment by flozero** [comment] 2023-03-29 22:12
Thanks for answering @devalevenkatesh .

So far my repo have eveyrthing migrate into react 18 that include:
- sdk
- ui
- all the providers

I found some potential issues that need to be investigate like background blur. But as we don't have the full plan from the aws chime I would guess its probably related to this.

I didn't add back the storyblok preview. But it something I can do. Would be happy to discuss with you more and show you the work if you are interested.

**Comment by xuesichao** [comment] 2023-04-21 17:02
Hi there, we wanted to give you an update on our react 18 support. We have recently updated our SDK to support React 18 in the `react-18 branch` of our GitHub repository, which you can find here: https://github.com/aws/amazon-chime-sdk-component-library-react/tree/react-18. While we are still in the process of migrating our storybook, the SDK itself has been fully upgraded.

Before we officially release this change, we would love to receive your feedback on this update. We appreciate any comments or suggestions you may have.

If you would like to give it a try here're the steps:
* check `out react-18` branch here: https://github.com/aws/amazon-chime-sdk-component-library-react/tree/react-18
* run `npm install`, `npm run build` and `npm pack`, a tarball file `amazon-chime-sdk-component-library-react-3.6.0.tgz` will be generated.
* Copy and paste this tarball in your project and run `npm install amazon-chime-sdk-component-library-react-3.6.0.tgz` to install it.
* Play with your project and see if it breaks anything.

Thank you for your support and patient!

**Comment by xuesichao** [comment] 2023-06-08 21:31
Hi all, we just published `amazon-chime-sdk-component-library-react@3.7.0` to npm. We added support for React 18 in this v3.7.0 version. Thanks again for your support and patience!

I'll close this issue for now, let us know if you run into any issue.

**Closed** 2023-06-08 21:31 UTC
Labels: feature-request
