### ISSUE TITLE
useFeaturedTileState stops working

### ISSUE THREAD

**Issue by jkelting** [aws/amazon-chime-sdk-component-library-react#315] opened 2020-12-02 13:51 UTC
I join a meeting with a couple of different attendees. For visual support of who is speaking the most active speaker has a red border around his videotile. I use the hook useFeaturedTileState() to get the featuredtileId of the most acitve speaker.
After a while this hook stops working. The hook return null as featuredTileId, which means my border is not shown anymore.

1. Start a meeting with a couple of attendees
2. log the tileId you get from useFeaturedTileState()
3. talk a while and check the logs
4. After some time the tileId is returned as null, even though someone is talking

**Expected behavior**
The hook useFeaturedTileState() should always return the tileId of the activee speaker

_

**Comment by bradmanAWS** [comment] 2020-12-03 17:47
Closing as this is a duplicate of https://github.com/aws/amazon-chime-sdk-js/issues/924

**Closed by bradmanAWS** 2020-12-03 17:47 UTC
Labels: Bug
