### ISSUE TITLE
useRosterState and useRemoteVideoTileState issue

### ISSUE THREAD

**Issue by pawanl77** [aws/amazon-chime-sdk-component-library-react#519] opened 2021-06-01 21:14 UTC
I have created a video application where I am using React chime sdk. In my application i need to update the server whenever a new participant video is shared.  I am detecting the change using useEffect hook in React.

I am currently using:
const { tiles, attendeeIdToTileId } = useRemoteVideoTileState(); 

useEffect(() => {
       //here I will do the api call
    }, [tiles]);

so what i have observed so far is whenever more than 1 tile are share....suppose 10 tiles are shared.. and someone unshare his video than useEffect runs 9 times. i found that the tiles was updtating 9 time....in this case... first time it contains 1 tile, then 2 and so on till 9.

My issue is the  external api gets called this 9 times. So why I am not gettting the value single time. Why the tiles is first 1,2,3...9.

Can anyone suggest any solution.

FYI, I have used the roster  array : 
               const { roster } = useRosterState();
and it had the same issue.

**Comment by xuesichao** [comment] 2021-12-22 00:33
Hi @pawanl77 , sorry for the late reply. This situation is not a bug but designed intentionally.

For `useRemoteVideoTileState()` hook, it uses the `videoTileDidUpdate` and `videoTileWasRemoved` callback functions from Amazon Chime SDK for JavaScript. These two callback functions only notify the video tile state once per function call. Check the code here:
https://github.com/aws/amazon-chime-sdk-js/blob/2e2c7e36631d898b925e6e341c28f72dafcfa8d6/src/audiovideoobserver/AudioVideoObserver.ts#L32-L40.

For `useRosterState()` hook, it uses the `RealtimeSubscribeToAttendeeIdPresenceCallback` callback function. It also update the state of one attendee per function call. Check the definition here:
https://github.com/aws/amazon-chime-sdk-js/blob/master/src/realtimecontroller/RealtimeSubscribeToAttendeeIdPresenceCallback.ts

So let say there's a meeting and there are 3 attendees, all of them are sharing the videos. Now there's a new attendee joined the meeting. At the moment this new attendee joins the meeting, the roster is empty and no video tiles. Now the `videoTilesStates` will be populated one tile by one tile. 
So the `tiles` will be updated three times: 
1. [tileId 1] 
2. [tileId 1, tileId 2]
3. [tileId 1, tileId 2, tileId 3]

>Note: Each attendee could have a different order of `tileIds`.

Same situation for `useRosterState()`.

So for your use case, I would recommend you to use the `videoTileDidUpdate` and `videoTileWasRemoved` callback function from Amazon Chime SDK for JavaScript. 

Some useful references:
1. Implementation of `useRosterState` hook for help.
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/main/src/providers/RemoteVideoTileProvider/index.tsx#L16-L51

2. Use case 14:
https://github.com/aws/amazon-chime-sdk-js#video

3. implementation of `VideoTileGridProvied` in https://github.com/aws-samples/amazon-chime-sdk
https://github.com/aws-samples/amazon-chime-sdk/blob/a24be0adfa9071639e4de1cb2967112dc26f2726/apps/meeting/src/providers/VideoTileGridProvider/state.tsx#L148-L185

What you need to do is:
1. Subscribe to `useRosterState()` hook and keep a list of attendees
2. Maintain the `videoEnabled` state of each attendee locally, including the self attendee.
3. Check if the `videoEnabled` state of attendees is changed, and if yes, make the API call

```js
const audioVideo = useAudioVideo();
const attendeeStates = {
  attendeeId1: {
    videoEnabled: true,
  },
  attendeeId2: {
    videoEnabled: false,
  }
}

useEffect(() => {
  if (!audioVideo) {
    return;
  }

  const observer: AudioVideoObserver = {
    videoTileDidUpdate: (tileState): void => {
    // Update `attendeeStates`
    },
    videoTileWasRemoved: (tileId): void => {
   // Update `attendeeStates`
    },
  };

  audioVideo.addObserver(observer);
  return () => audioVideo.removeObserver(observer);
}, [audioVideo]);
```

**Comment by xuesichao** [comment] 2021-12-22 00:33
Close the issue for now, if you still have questions feel free to reopen it.

**Closed by xuesichao** 2021-12-22 00:33 UTC
Labels: Bug
