### ISSUE TITLE
issues with meetingManager.start() when following demo linked from repo

### ISSUE THREAD

**Issue by Jason-Reich** [aws/amazon-chime-sdk-component-library-react#345] opened 2020-12-28 02:14 UTC
**Describe the bug**
When following the demo linked from "Chime SDK UI Component Library Documentation" on the aws/amazon-chime-sdk-component-library-react repo, I always end up with " [WARN] SDK - signaling connection closed by server with code 4403 and reason: attendee unavailable" when I get to meetingManager.start().

_Please note that this is not because there is only one user joining the meeting (I tried with two users)... and this is also not because meetingManager.start() was called "too soon"... I intentionally did tests where I didn't call meetingManager.start until some time had passed after meetingManager.join(joinData) succeeded!_

Note: I seem to very briefly join the meeting and then instantly the websocket closes (at least that's what I think is going wrong).

**To Reproduce**
Do steps 1, 2, and 3 *exactly* as shown under the "Introduction" (the Introduction at the very top--  https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/introduction--page) of the "Chime SDK UI Component Library Documentation" and you should get the error (I'm referring to steps 1, 2, and 3 of the section titled "Getting Started").

**Expected behavior**
I would expect to not get the above error so that I could remain connected, start video, and so on.

**Screenshots**

The log attached below from my browser console (with logLevel={LogLevel.DEBUG}) shows everything... including a console.log of the meetingInfo and attendeeInfo data coming back from my node.js Lambda backend for this part of the demo guide:

```
      const joinData = {
      meetingInfo: meetingInfo,
      attendeeInfo: attendeeInfo,
    };

    // Use the join API to create a meeting session
    await meetingManager.join(joinData);
```

[localhost2-1609119084728.log](https://github.com/aws/amazon-chime-sdk-component-library-react/files/5745618/localhost2-1609119084728.log)

**Desktop (please complete the following information):**
 - OS: macOS Catalina Version 10.15.7
 - Browser Chrome
 - Version 87.0.4280.88

**Comment by p-foucht** [comment] 2020-12-28 22:08
Hi @Jason-Reich 

That sounds like some kind of backend error. How are you creating your meeting and attendee?

**Comment by Jason-Reich** [comment] 2020-12-28 22:56
@p-foucht I literally did exactly what I wrote above. (And the response from creating my meeting and attendee is in the attachment... i.e. I provide, in the attachment, a console.log of what my Lambda function returned). For now I'm setting this aside so no need to dig on my account. But if there are other issues coming that are somehow similar to what I described, maybe it will be worth going through what I described above with a blank project-- exactly as the demo steps [mentioned above] instruct. (There might be an issue with the demo/library... but I admit that it could be just me... so like I said, if the above isn't useful then feel free to disregard it).

**Comment by p-foucht** [comment] 2021-01-25 17:37
Gotcha -- I haven't been able to repro this following the steps in the docs. I'll leave this ticket up in case others experience the issue can post here and we can further root cause

**Comment by p-foucht** [comment] 2021-02-18 17:23
Closing as there has been no other activity. Will reopen if other reports come in

**Closed by p-foucht** 2021-02-18 17:23 UTC
Labels: Needs More Information

**Comment by jacobikedichi** [comment] 2021-11-01 16:37
I'm experiencing this same exact problem. Was anyone able to figure out what was causing the error? And more importantly how to fix the error?

**Comment by vitaliy-bobrov-mev** [comment] 2022-12-09 17:42
+1 Faced with the same issue

**Comment by michhyun1** [comment] 2022-12-09 19:12
Please take a look at our example meeting demo: https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/meeting/src/containers/MeetingForm/index.tsx#L73-L133
