### ISSUE TITLE
Tooltips dont work

### ISSUE THREAD

**Issue by OriginLive** [aws/amazon-chime-sdk-component-library-react#445] opened 2021-03-05 08:00 UTC
**Describe the bug**
Using tooltipable items or wrapping a component itself does not actually show the tooltip.

Even worse, ControlBarItem was renamed to ControlBarButton, but the filename and documentation still points to ControlBarItem

src/components/ui/ControlBar/ControlBarItem.tsx
https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/ui-components-controlbar--control-bar

If you click on the Documentation button above, you can see it says
"ControlBars support tooltips on any buttons by adding a data-tooltip property. Adding a data-tooltip-position property controls the tooltip position".

If you wrap the abovementioned item, you already have a label prop which prevents you from using the tooltip.

Nor is there any documentation on using Tooltips anywhere in the storybook.

**To Reproduce**
1. Import any element and wrap it with WithTooltip.
2. const YourTooltipElement = WithTooltip(YourElement)
2. Apply label and/or other props
3. See that there is no tooltip

**Expected behavior**
Expecting a tooltip to show,
trying to implement a tooltip on ControlBarButton (ex Item) in ControlBar

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser latest chrome
 - "amazon-chime-sdk-component-library-react": "^2.1.0",
 - "amazon-chime-sdk-js": "^2.5.0",

**Additional context**
Please update your documentation, typescript definition of files and whether they're tooltippable or not and fix the tooltipping, thanks!.

**Comment by ltrung** [comment] 2021-03-10 04:49
@OriginLive Thanks for reporting this. I have been able to reproduce the tooltip does not show in ControlBarButton. However, could you clarify what you meant by the following:
> If you wrap the abovementioned item, you already have a label prop which prevents you from using the tooltip.

**Comment by OriginLive** [comment] 2021-03-10 10:54
Hi,

so for ControlBarButton

it has the following props:
```
export const ControlBarButton: FC<ControlBarButtonProps> = ({
  icon,
  onClick,
  label,
  isSelected = false,
  popOver = null,
  popOverPlacement,
  popOverLabel,
  children,
  ...rest
}) => {
```

while the wrapper for tooltip has the following props
```
export interface ToolTipProps {
  label: string;
  tooltipPosition?: ToolTipPositionType;
}
```

both have a prop named label and you can't change the label on the tooltip without affecting what's written bellow the controllbar item, which is not desirable!

Also tooltip should accept a component and a string for label like how material input does, because we would like to have a header and description on the tooltip (with a different style tooltip as well)


Another thing that would be nice to have is if UserActivityContext would be exported in index (currently i cannot import it in my react app), or if we could get a way to tap into UserActivityProvider state because i would like to show activity on a custom keypress.

Here's an example of what we're trying to achieve:
![image](https://user-images.githubusercontent.com/24319526/110618786-5e798880-8197-11eb-91ad-9c4911fe9927.png)

**Comment by ltrung** [comment] 2021-03-11 23:25
@OriginLive Thanks for the detailed explanation. Looking at how we implement tooltip right now, it will render the tooltip in a container element outside of the React app using [createPortal](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/ui/WithTooltip/index.tsx#L65). The container is specified using the [element id](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/ui/WithTooltip/index.tsx#L32). However, all components that support tooltip does not allow to specify this container id currently (e.g., [ControlBarButton](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/ui/ControlBar/ControlBarItem.tsx#L15)).
Right now we assume the container Id to be `Tooltip__container` if it is not passed in. I added a div with id=`Tooltip__container` in our meeting demo [here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/demo/meeting/app/meeting.html#L12) and verified that the tooltip showed up.

We also do not allow builders to specify tooltip content as you said.

**Comment by p-foucht** [comment] 2021-03-26 19:30
Hey @OriginLive

The above linked commit should address the main points you brought up -

- For components wrapped with `WithTooltip`, you should be able to pass a `tooltipContent` prop. If you don't pass one, it falls back to the `label`
- `tooltipContent` accepts a component and not just a string
- Added a warning log to let developers know if we don't find a container element when trying to render the tooltip into a portal
- Allow for tooltip container ID to be passed through components that are internally using `WithTooltip`

Let us know if that works for you

**Comment by devalevenkatesh** [comment] 2021-04-12 17:27
Hello @OriginLive ,

We are closing this issue since it has been released already. Please feel free to create a new issue if you face any issue.
Thanks again for reporting this.

**Closed by devalevenkatesh** 2021-04-12 17:27 UTC
Labels: Bug, Enhancement, Triaged
