### ISSUE TITLE
onDeviceReplacement don't work well in the macbook

### ISSUE THREAD

**Issue by andreMycroft** [aws/amazon-chime-sdk-component-library-react#864] opened 2023-01-07 22:20 UTC
### What happened and what did you expect to happen?

When I turn of my Wifi for some reason the onDeviceReplacement it's called, maybe because he lost the connection with the deviceList of the macbook.
So this way when i connect back he get's the next device Normally the default.
The big problem is, If my DeviceLabel it's None, he ignore that and turn on my audio.
So i expect that the lib check if the current Attendee have permissions to use audio before do that.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

Join a Meeting with Two Attendee without audio `DeviceLabel.None` 
Turn off the wifi on Macbook
Turn On the Wifi on Macbook

### Amazon Chime SDK React Components Library version

3.3.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 108.0.5359.124 (Official Build) (arm64)

### Device Information

Macbook M1 2020

### Important now it's setting `Null` because i change the `onDeviceReplacement` to allways return null.

2023-01-07T22:18:47.790Z [INFO] ChimeSDKReactComponent - Device change event callback is triggered
ConsoleLogger.js:78 2023-01-07T22:18:47.829Z [INFO] ChimeSDKReactComponent - AudioInputProvider - audio inputs updated
ConsoleLogger.js:78 2023-01-07T22:18:47.832Z [INFO] ChimeSDKReactComponent - API/DefaultAudioVideoFacade/6a3741ea-2e57-4526-9d43-9fbf547a0706/7afb821f-8913-ce8d-efa9-ad45f71dd8e8/startAudioInput null
ConsoleLogger.js:78 2023-01-07T22:18:47.834Z [INFO] ChimeSDKReactComponent - Choosing intrinsic audio input device null
ConsoleLogger.js:78 2023-01-07T22:18:47.834Z [INFO] ChimeSDKReactComponent - reusing existing audio input device
ConsoleLogger.js:78 2023-01-07T22:18:47.835Z [INFO] ChimeSDKReactComponent - API/DefaultDeviceController/startAudioInputDevice null -> "success"
ConsoleLogger.js:78 2023-01-07T22:18:47.835Z [INFO] ChimeSDKReactComponent - Receive an audio input change event
ConsoleLogger.js:78 2023-01-07T22:18:47.847Z [INFO] ChimeSDKReactComponent - AudioInputProvider - audio inputs updated
ConsoleLogger.js:78 2023-01-07T22:18:47.847Z [INFO] ChimeSDKReactComponent - API/DefaultAudioVideoFacade/8cb273cb-5461-4e17-bda6-384675e90706/b071b964-f543-ceac-2392-1541572461a5/startAudioInput null
ConsoleLogger.js:78 2023-01-07T22:18:47.848Z [INFO] ChimeSDKReactComponent - Choosing intrinsic audio input device null
ConsoleLogger.js:78 2023-01-07T22:18:47.848Z [INFO] ChimeSDKReactComponent - reusing existing audio input device
ConsoleLogger.js:78 2023-01-07T22:18:47.848Z [INFO] ChimeSDKReactComponent - API/DefaultDeviceController/startAudioInputDevice null -> "success"
ConsoleLogger.js:78 2023-01-07T22:18:47.848Z [INFO] ChimeSDKReactComponent - Receive an audio input change event
ConsoleLogger.js:78 2023-01-07T22:18:47.850Z [INFO] ChimeSDKReactComponent - Local audio input is updated
ConsoleLogger.js:78 2023-01-07T22:18:47.851Z [INFO] ChimeSDKReactComponent - Local audio input is updated
ConsoleLogger.js:78 2023-01-07T22:18:50.950Z [INFO] ChimeSDKReactComponent - peer connection ice connection state changed: disconnected
ConsoleLogger.js:78 2023-01-07T22:18:50.951Z [INFO] ChimeSDKReactComponent - peer connection state changed: disconnected
ConsoleLogger.js:78 2023-01-07T22:18:53.215Z [INFO] ChimeSDKReactComponent - peer connection ice connection state changed: disconnected
ConsoleLogger.js:78 2023-01-07T22:18:53.215Z [INFO] ChimeSDKReactComponent - peer connection state changed: disconnected
ConsoleLogger.js:78 2023-01-07T22:18:57.383Z [INFO] ChimeSDKReactComponent - Device change event callback is triggered
ConsoleLogger.js:78 2023-01-07T22:18:57.384Z [INFO] ChimeSDKReactComponent - Device change event callback is triggered
ConsoleLogger.js:78 2023-01-07T22:18:57.401Z [INFO] ChimeSDKReactComponent - AudioInputProvider - audio inputs updated
ConsoleLogger.js:78 2023-01-07T22:18:57.401Z [INFO] ChimeSDKReactComponent - API/DefaultAudioVideoFacade/6a3741ea-2e57-4526-9d43-9fbf547a0706/7afb821f-8913-ce8d-efa9-ad45f71dd8e8/startAudioInput null
ConsoleLogger.js:78 2023-01-07T22:18:57.402Z [INFO] ChimeSDKReactComponent - Choosing intrinsic audio input device null
ConsoleLogger.js:78 2023-01-07T22:18:57.402Z [INFO] ChimeSDKReactComponent - reusing existing audio input device
ConsoleLogger.js:78 2023-01-07T22:18:57.402Z [INFO] ChimeSDKReactComponent - API/DefaultDeviceController/startAudioInputDevice null -> "success"
ConsoleLogger.js:78 2023-01-07T22:18:57.402Z [INFO] ChimeSDKReactComponent - Receive an audio input change event
ConsoleLogger.js:78 2023-01-07T22:18:57.404Z [INFO] ChimeSDKReactComponent - Local audio input is updated
ConsoleLogger.js:78 2023-01-07T22:18:57.413Z [INFO] ChimeSDKReactComponent - AudioInputProvider - audio inputs updated
ConsoleLogger.js:78 2023-01-07T22:18:57.414Z [INFO] ChimeSDKReactComponent - API/DefaultAudioVideoFacade/8cb273cb-5461-4e17-bda6-384675e90706/b071b964-f543-ceac-2392-1541572461a5/startAudioInput null
ConsoleLogger.js:78 2023-01-07T22:18:57.414Z [INFO] ChimeSDKReactComponent - Choosing intrinsic audio input device null
ConsoleLogger.js:78 2023-01-07T22:18:57.414Z [INFO] ChimeSDKReactComponent - reusing existing audio input device
ConsoleLogger.js:78 2023-01-07T22:18:57.414Z [INFO] ChimeSDKReactComponent - API/DefaultDeviceController/startAudioInputDevice null -> "success"
ConsoleLogger.js:78 2023-01-07T22:18:57.414Z [INFO] ChimeSDKReactComponent - Receive an audio input change event
ConsoleLogger.js:78 2023-01-07T22:18:57.416Z [INFO] ChimeSDKReactComponent - Local audio input is updated
InMemoryJSONEventBuffer.js:384          POST https://data.svc.ue1.ingest.chime.aws/v1/client-events net::ERR_INTERNET_DISCONNECTED
(anonymous) @ InMemoryJSONEventBuffer.js:384
(anonymous) @ InMemoryJSONEventBuffer.js:29
__webpack_modules__../node_modules/amazon-chime-sdk-js/build/eventbuffer/InMemoryJSONEventBuffer.js.__awaiter @ InMemoryJSONEventBuffer.js:11
send @ InMemoryJSONEventBuffer.js:379
(anonymous) @ InMemoryJSONEventBuffer.js:96
(anonymous) @ InMemoryJSONEventBuffer.js:29
__webpack_modules__../node_modules/amazon-chime-sdk-js/build/eventbuffer/InMemoryJSONEventBuffer.js.__awaiter @ InMemoryJSONEventBuffer.js:11
InMemoryJSONEventBuffer.sendEvents @ InMemoryJSONEventBuffer.js:75
(anonymous) @ InMemoryJSONEventBuffer.js:186
react_devtools_backend.js:4012 2023-01-07T22:18:57.875Z [WARN] ChimeSDKReactComponent - Event Reporting - InMemoryJSONEventBuffer - sendEvents - Error in sending events {"metadata":{"browserName":"Chrome","browserVersion":"108.0.0.0","deviceName":"Unavailable","osName":"Mac OS","osVersion":"10.15.7","sdkVersion":"3.9.0","sdkName":"amazon-chime-sdk-js","meetingId":"8cb273cb-5461-4e17-bda6-384675e90706","attendeeId":"b071b964-f543-ceac-2392-1541572461a5"},"events":[{"type":"Meet","v":1,"payloads":[{"name":"audioInputSelected","ts":1673129927848},{"name":"audioInputSelected","ts":1673129937414}]}]} to the ingestion endpoint TypeError: Failed to fetch
overrideMethod @ react_devtools_backend.js:4012
log @ ConsoleLogger.js:72
warn @ ConsoleLogger.js:38
(anonymous) @ InMemoryJSONEventBuffer.js:112
rejected @ InMemoryJSONEventBuffer.js:21
Promise.then (async)
step @ InMemoryJSONEventBuffer.js:27
(anonymous) @ InMemoryJSONEventBuffer.js:29
__webpack_modules__../node_modules/amazon-chime-sdk-js/build/eventbuffer/InMemoryJSONEventBuffer.js.__awaiter @ InMemoryJSONEventBuffer.js:11
InMemoryJSONEventBuffer.sendEvents @ InMemoryJSONEventBuffer.js:75
(anonymous) @ InMemoryJSONEventBuffer.js:186
react_devtools_backend.js:4012 2023-01-07T22:18:58.284Z [WARN] ChimeSDKReactComponent - missed pong 1 time(s)
overrideMethod @ react_devtools_backend.js:4012
log @ ConsoleLogger.js:72
warn @ ConsoleLogger.js:38
ping @ DefaultPingPong.js:67
(anonymous) @ DefaultPingPong.js:56
ConsoleLogger.js:78 2023-01-07T22:18:58.465Z [INFO] ChimeSDKReactComponent - peer connection ice connection state changed: connected
ConsoleLogger.js:78 2023-01-07T22:18:58.465Z [INFO] ChimeSDKReactComponent - peer connection state changed: connected
ConsoleLogger.js:78 2023-01-07T22:18:58.486Z [INFO] ChimeSDKReactComponent - peer connection ice connection state changed: connected
ConsoleLogger.js:78 2023-01-07T22:18:58.486Z [INFO] ChimeSDKReactComponent - peer connection state changed: connected

**Comment by devalevenkatesh** [comment] 2023-02-10 06:01
Sorry for the delay in response. When setting `DeviceLabel.None`, you should be joining in view-only or spectator mode. I tried to follow your reproduction steps and could not reproduce the issue.

1. Could you be able to check our below demo and see whether you can reproduce this issue?
https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting
2. Here is some documentation on view-only mode that can help or if you are trying to customize the device label trigger: https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/quick-starts--page

One thing is unless your permissions are allowed, Chime component library would not be able to actually use any audio. Cause it will result into Permissions denied failure when attemping to select device.

There is no standard / good way to understand user permissions on devices using browser APIs as of yet. Thus thats the limitations with browsers.

**Comment by devalevenkatesh** [comment] 2023-03-29 21:20
The fix for this is merged and will be released in next component library release. I will close this issue after the release.

**Comment by xuesichao** [comment] 2023-04-28 19:01
Change is released in v3.6.0 yesterday. Closing this now, thank you.

**Closed by xuesichao** 2023-04-28 19:01 UTC
Labels: Triaged
