### ISSUE TITLE
[FEATURE REQUEST] override div styles inside UserActivityProvider 

### ISSUE THREAD

**Issue by israelKusayev** [aws/amazon-chime-sdk-component-library-react#702] opened 2021-12-16 10:59 UTC
Is it possible to add props to UserActivityProvider to override the styles of that div? 
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/61464e15175b0f88d141f968790524c5443ea5d1/src/providers/UserActivityProvider/index.tsx#L30)

**Comment by xuesichao** [comment] 2021-12-16 21:39
Hi @israelKusayev . I don't think the SDK supports this now. What kind of result do you want to achieve?

**Comment by israelKusayev** [comment] 2021-12-17 07:43
I had some styling issues, I needed to set the height of the video container to be fullscreen
in order to do that I need to give 100% height to every div until the body (I had some problems with 100vh)
that why it would be nice to have control over `UserActivityProvider ` div


my current solution is to wrap the div inside another div in order to solve it
```javascript
export const MeetingContainer = styled('div')({
	height: '100%',

	'> div': {
		height: '100%'
	}
});
```

**Comment by xuesichao** [comment] 2021-12-21 23:03
We are trying to improve the entire style system in next major version, tracked #196 . Leave this issue open as a feature request for now.

**Comment by vidya-mohan** [comment] 2022-01-06 17:33
Tracking as dupe of https://github.com/aws/amazon-chime-sdk-component-library-react/issues/196 so resolving this for now

**Closed by vidya-mohan** 2022-01-06 17:33 UTC
Labels: feature-request
