### ISSUE TITLE
"Cannot select audio output device. This browser does not support setSinkId."

### ISSUE THREAD

**Issue by mariaines** [aws/amazon-chime-sdk-component-library-react#365] opened 2021-01-08 19:56 UTC
**Describe the bug**
Hi there,

First of all thank you for this library, I was able to get a prototype working in a few hours!  So cool!

I'm seeing this issue when trying to join and start a meeting in a mobile browser (chrome). I don't understand why it is being thrown since Chrome should support setSinkId. But this issue in the main repo: https://github.com/aws/amazon-chime-sdk-js/issues/932 suggests this is expected and you can try/catch the error and audio should still work, so perhaps that is a solution?

**To Reproduce**
- Join and start a meeting on Android Chrome browser
- See console error for uncaught exception from main repo: "Cannot select audio output device. This browser does not support setSinkId."

**Expected behavior**
Can join and hear audio on Android Chrome

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 11 (RQ1A.201205.003)
 - Browser: Chrome
 - Version: 87.0.4280.141

**Comment by RidipDe** [comment] 2021-01-11 07:57
Can you please confirm the Amazon Chime SDK version you are using?

**Comment by RalphLincoln** [comment] 2021-01-11 10:10
How soon will this be resolved?

**Comment by mariaines** [comment] 2021-01-11 20:03
@RidipDe sorry, I still don't understand the problem. If we can't manually choose the audio output device, can we just default to some default? Or show some friendly error instead of failing to the join the meeting at all?

> https://webrtc.github.io/samples/src/content/devices/multi/

^^ This sample works for me on Android Chrome

**Comment by harrycollin** [comment] 2021-01-12 12:53
I'm also getting this on Firefox. These are the errors from the console. 

Browser: Firefox
OS: Windows 10
Version: 84.0.2 (64-bit)

`Uncaught (in promise) Error: Cannot select audio output device. This browser does not support setSinkId.
    bindAudioMix DefaultAudioMixController.js:117
    __awaiter DefaultAudioMixController.js:32
    __awaiter DefaultAudioMixController.js:11
    bindAudioMix DefaultAudioMixController.js:106
    bindAudioElement DefaultAudioMixController.js:56
    __awaiter DefaultAudioMixController.js:32
    __awaiter DefaultAudioMixController.js:11
    bindAudioElement DefaultAudioMixController.js:52
    bindAudioElement DefaultAudioVideoFacade.js:81
    LocalAudioOutputProvider index.esm.js:9486
    React 6
    unstable_runWithPriority scheduler.development.js:656
    React 4
    unstable_runWithPriority scheduler.development.js:656
    React 5
    joinMeeting MeetingWidget.tsx:112
    onClick MeetingWidget.tsx:175
    React 17
    unstable_runWithPriority scheduler.development.js:656
    React 4
DefaultAudioMixController.js:117
`

and 

``

**Comment by jrowny** [comment] 2021-01-21 18:19
This issue is also a blocker for me, need to be able to join a meeting from mobile.

**Comment by jrowny** [comment] 2021-01-21 20:51
I haven't tested this yet, but in theory, this could be a workaround:

TypeScript:
```
// Fake Polyfill setSinkId so mobile devices can use Chime
if(!('setSinkId' in HTMLAudioElement.prototype)) {
  (HTMLAudioElement.prototype as any).setSinkId = () => {
    // noop
  }
}

```

For javascript just remove the "as any"

**Comment by richnew10** [comment] 2021-01-21 22:13
It looks like in this case, @jrowny and @mariaines, `npm` is installing `2.4` instead of `1.22` despite the latter being the dependency listed in `package.json`. The peer dependency is unfortunately inaccurate, and seems to be overriding the explicit dependency.

A change to the component library to switch over to SDK 2.x is in progress.

While we address both of those things, I recommend you **temporarily** take an explicit dependency on 1.22:

```
 npm install --save "amazon-chime-sdk-js@1.22.0"
```

Please undo this when we close this ticket; we'll remind you.

**Comment by anuranduttaroy** [comment] 2021-01-22 05:47
We have an open PR https://github.com/aws/amazon-chime-sdk-component-library-react/pull/392 to fix this issue. Can you try to pull the latest changes from [audio-output-fix](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/audio-output-fix) branch and see if that resolves your issue?

**Comment by anuranduttaroy** [comment] 2021-01-23 02:28
The fix for this issue has been merged to master branch. Could everyone here facing this issue try to see if the fix resolved your issue?

**Comment by vidya-mohan** [comment] 2021-01-23 22:03
@mariaines @RalphLincoln @jrowny @harrycollin - the hotfix for the issue is merged on https://www.npmjs.com/package/amazon-chime-sdk-component-library-react 1.16.1.

Could you please sync and verify the fix?

**Comment by mariaines** [comment] 2021-01-23 22:39
Verified! Thanks for the quick fix! 🚀

**Comment by vidya-mohan** [comment] 2021-01-23 23:15
Thank you - appreciated the quick response! Resolving this ticket - thank you for your interest in the SDK.

**Closed by vidya-mohan** 2021-01-23 23:15 UTC
Labels: Bug
