### ISSUE TITLE
webcam camera lights still on after quitting meeting 

### ISSUE THREAD

**Issue by amardeep24** [aws/amazon-chime-sdk-component-library-react#604] opened 2021-09-02 15:51 UTC
### What happened and what did you expect to happen?

When a participant leaves the meeting by calling the `MeetingManager.leave()`, the cleanup does not happen as expected. The `MeetingManager.leave()` is supposed to clean up all the resources, bindings, and the open `MediaTrack` resources. This should have turned off the webcam light.

The correct behavior is seen when we delete the chime meeting from the backend. In this case, the resources are cleaned up properly. The problem occurs when one participant leaves the meeting.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

Step 1: Join the meeting by calling `MeetingManager.join(joinInfo)`

Step 2: Start audio/video stream by calling `MeetingManager.start()`

Step 3: Call `MeetingManager.leave()` to leave the meeting and also call chime backend API.

Step 4: The meeting video is stopped but the webcam light is still on.

### Amazon Chime SDK React Components Library version

2.8.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 93.0.4577.63 (Official Build) (x86_64)

### Device Information

macOS Big Sur 11.4

### Meeting and Attendee ID Information.

```
{
  "meeting": {
    "meetingId": "dcd32ca2-34bf-4049-a7b5-925be0eb0706",
    "externalMeetingId": "ad927913-fedb-4ddd-8506-840f7cf28ddb",
    "mediaPlacement": {
      "audioHostUrl": "0307003aa242bb954d28cbd581b9dba3.k.m2.ue1.app.chime.aws:3478",
      "audioFallbackUrl": "wss://haxrp.m2.ue1.app.chime.aws:443/calls/dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "screenDataUrl": "wss://bitpw.m2.ue1.app.chime.aws:443/v2/screen/dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "screenSharingUrl": "wss://bitpw.m2.ue1.app.chime.aws:443/v2/screen/dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "screenViewingUrl": "wss://bitpw.m2.ue1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "signalingUrl": "wss://signal.m2.ue1.app.chime.aws/control/dcd32ca2-34bf-4049-a7b5-925be0eb0706",
      "turnControlUrl": "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions",
      "eventIngestionUrl": null
    },
    "mediaRegion": "us-east-1"
  },
  "attendee": {
    "externalUserId": "9130354383887926",
    "attendeeId": "4b45c6b4-ff2d-d60c-6aa1-be4936ca1d58",
    "joinToken": "NGI0NWM2YjQtZmYyZC1kNjBjLTZhYTEtYmU0OTM2Y2ExZDU4OjM0N2RmYmRmLTQxYzYtNDkwNS04YjA0LWU3NWZlNjRmNjhmOA"
  }
}
```

### Browser console logs

No new logs are seen on the meeting disconnect

**Comment by subhendukundu** [comment] 2021-09-07 11:18
We are facing something similar behaviour when the component unmount. **_Happens sometimes_**.
So basically if someone goes to homepage directly, without leaving the meeting, the camera lights still on.

```
useEffect(() => {
      async function leaveMeeting() {
        await meetingManager.leave();
      }
      return () => {
        leaveMeeting();
      };
    }, [meetingManager]);
 ```

**Comment by devalevenkatesh** [comment] 2021-09-08 01:14
Hi @amardeep24 and @subhendukundu ,

Thanks for reporting this issue. I think the issues mentioned here are different, one is when say a user goes to a previous page and never calls `meetingManager.leave()`, I could see it in the demo app that the Webcam camera stays on.

In the demo app, we have a leave button, upon clicking it[1](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/meeting/src/containers/EndMeetingControl/index.tsx#L28) we re-direct to home page and that calls `meetingManager.leave()`[2](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/meeting/src/providers/NavigationProvider.tsx#L45-L51). I could not reproduce the issue with the demo app. The Webcam turned off as expected.

So, @amardeep24 could you please clarify more on questions below:
1. Are you facing the same issue as pointed out by @subhendukundu in previous comment? I guess not as you are calling `meetingManager.leave()`, but want to check again.
2. Are you using `await` as the `meetingManager.leave()` returns a promise?
3. Are you using any video preview feature? If so, we currently do not call `stopVideoPreviewForVideoInput()` in the `leave()` function and only do it in the [`PreviewVideo`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/components/sdk/PreviewVideo/index.tsx#L53) SDK connected component.
4. But, to stop the Webcam light we stop local video and choose the video input device as `null`. We have an FAQ in the `amazon-chime-sdk-js` on the same issue. [FAQ link](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#after-leaving-a-meeting-the-camera-led-is-still-on-indicating-that-the-camera-has-not-been-released-what-could-be-wrong). As suggested we do the same in the `leave()` function [here](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/MeetingProvider/MeetingManager.ts#L211-L233). Hence, wondering if there is a separate workflow or some call we are missing there.
5. Could you please clarify how you start the video and whether you stop it or rely on the `leave()` to clear it for you? Is this video just a preview one start using `startVideoPreviewForVideoInput`?
6. Are you using the library [`LocalVideo`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-localvideo--page), [`RemoteVideo`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-remotevideo--page) or [`PreviewVideo`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-components-previewvideo--page) components or building your own?

Sorry for many questions, we want to understand the issue a little bit more.

**Comment by amardeep24** [comment] 2021-09-09 06:17
Hi @devalevenkatesh,

Thanks for responding, please find the queries answered below:
1. We are calling the `meetingManager.leave()` so i don't think the issue is the same.
2. Yes we are using `await` before the `meetingManager.leave()`.
3. No we are not using any video preview feature.
4. I went through the FAQ you mentioned and saw that the `meetingManager.leave()`  does all that. So it should have cleaned up all the resources.
5. There is no preview in our use case. We call `await meetingManager.join(joinInfo)`  and then we do `await meetingManager.start()` this starts the local video.
6. Yes we are using the components from the React SDK: `LocalVideo` and `RemoteVideo`.

We implemented a custom hook for the leave meeting functionality, we do two things: we call `meetingManager.leave()` to clean up the media resources and then call our backend API to delete the attendee.

For reference this is our custom hook:

```
export default function useLeaveMeeting() {
  const [leftMeeting, setLeftMeeting] = useState<boolean>(false);
  const [status, setStatus] = useState<number>(0);
  const [error, setError] = useState<Error>(null);
  const leaveMeetingCallback = useCallback(() => setLeftMeeting(true), []);
  const meetingManager = useMeetingManager();

  useEffect(() => {
    const leaveMeeting = async () => {
      try {
        //...await on our backend API call
        await meetingManager.leave();
        setStatus(1);
      } catch (err) {
        setStatus(2);
        setError(err);
      }
    };
    if (leftMeeting) {
      leaveMeeting();
    }
  }, [ leftMeeting, meetingManager]);
  return {
    leaveMeeting: leaveMeetingCallback,
    status,
    error,
  };
}
```
The `leaveMeeting` on invocation of a click listener is doing the leave meeting action.

**Comment by devalevenkatesh** [comment] 2021-09-09 18:49
Hi @amardeep24 ,

To provide the INFO level browser console logs, please check you set the `logLevel` to `LogLevel.INFO` when passing the `MeetingProvider` props. By default, we set it to `LogLevel.WARN` hence the log won't be verbose enough to debug this further.

**Comment by devalevenkatesh** [comment] 2021-10-01 21:18
We root caused this to be the issue with the `useSelectVideoInputDevice` hook. We have merged in the PR to update the documentation and usage example to help builders know when to use this hook.

Closing this issue now.

**Closed by devalevenkatesh** 2021-10-01 21:18 UTC
