### ISSUE TITLE
RosterProvider Audio Sign Issue

### ISSUE THREAD

**Issue by pawanlakhera77** [aws/amazon-chime-sdk-component-library-react#259] opened 2020-10-23 20:16 UTC
Recently I was using the RosterProvider in the React Chime library. I found that when I was toggling the video the Roster updated well and shows the cross sign on video icon when it is not shown but for the audio even when Audio is off it is always showing the active icon in the Roster Window. Is this a bug?

**Comment by devalevenkatesh** [comment] 2020-10-27 01:08
Hello @pawanlakhera77 ,

I checked the [demo meeting app](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting) using chrome and react-devtools. I could see that the icon gets updated properly with the attendee `muted` status toggling correctly between `true` and `false` on mute and un-mute button click. I could not reproduce this issue. Can you please provide some more details about:
1. browser
2. browser version
3. OS

Also can you please check if you are facing the same issue by running the [demo meeting app](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting)?

**Comment by michhyun1** [comment] 2020-11-25 19:45
@pawanlakhera77 could you please verify if this is still happening for you? I cannot reproduce this issue. I will close this ticket, but please re-open if the issue is still a concern.

**Closed by michhyun1** 2020-11-25 19:45 UTC
Labels: Needs More Information, Question
