### ISSUE TITLE
How to keep camera on by default while joining the call?

### ISSUE THREAD

**Issue by arpitmittal-lab** [aws/amazon-chime-sdk-component-library-react#701] opened 2021-12-16 08:56 UTC
### What are you trying to do?

I am trying to join the meeting with my camera in open state.

**Comment by xuesichao** [comment] 2021-12-16 22:23
Hi @arpitmittal-lab , could you please check issue #544 and let us know if this can help you achieve it?

**Comment by arpitmittal-lab** [comment] 2021-12-17 09:56
Tried with the below code, but having issues like Black screen majority of the time.
{
.....
.......
await meetingManager.start();
toggleVideo();
.......
.....
}

**Alternate Code I tried**:
 
Earlier I tried having the toggle video inside useEffect, but it is having black screen issue after trying 5-6 times.

	useEffect(() => {
		if (!isVideoEnabled && meetingStatus === 1) {
			toggleVideo();
		}
	}, [isVideoEnabled, meetingStatus);

**Issue with alternate code**: Local video is working fine, but the user on other side gets the black screen.

**Comment by xuesichao** [comment] 2021-12-17 18:30
Got it, thanks for your detailed information. I will try to reproduce the issue and come back later.

**Comment by devalevenkatesh** [comment] 2021-12-17 23:08
I suggest trying below code where you have to check for the remote tiles using the [`useRemoteVideoTileState()`](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-useremotevideotilestate--page) hook.

https://github.com/devalevenkatesh/test-amazon-chime-sdk-react-components/blob/main/src/Home.tsx

Please let me know if you into any issue.

**Comment by arpitmittal-lab** [comment] 2021-12-21 09:59
@devalevenkatesh 

I have updated the code as suggested still facing the same issue of black video (After 5-6 attempts)

**Comment by devalevenkatesh** [comment] 2021-12-23 23:46
@arpitmittal-lab Can you please clarify what do you mean by "After 5-6 attempts"?

Also, will request your code to better understand the API or you can put some pseudo-code further to help. What happens if you try the above linked repo, even without changing anything there you are facing the issue?

**Comment by devalevenkatesh** [comment] 2021-12-23 23:55
Closing this issue as the camera on at the start has been solved now. For the black remote video lets discuss in #694 .

**Closed by devalevenkatesh** 2021-12-23 23:55 UTC
Labels: Needs More Information

**Comment by kapilmyakal** [comment] 2022-02-14 03:33
@devalevenkatesh  please suggest me solution for attendee video blinking 
ConsoleLogger.ts:82 2022-02-11T10:36:08.102Z [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b was canceled due to subtask AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b/Timeout15000ms error: serial group task AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b/Timeout15000ms/UpdateSession/SetLocalDescriptionTask error: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='1'.
log @ ConsoleLogger.ts:82
warn @ ConsoleLogger.ts:40
handleMeetingSessionStatus @ DefaultAudioVideoController.ts:1298
(anonymous) @ DefaultAudioVideoController.ts:1073
perform @ DefaultSessionStateController.ts:86
(anonymous) @ DefaultAudioVideoController.ts:1066
rejected @ DefaultAudioVideoController.ts:3
Promise.then (async)
step @ DefaultAudioVideoController.ts:3
(anonymous) @ DefaultAudioVideoController.ts:3
push../node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter @ DefaultAudioVideoController.ts:3
actionUpdateWithRenegotiation @ DefaultAudioVideoController.ts:1042
(anonymous) @ DefaultAudioVideoController.ts:780
perform @ DefaultSessionStateController.ts:86
update @ DefaultAudioVideoController.ts:779
resubscribe @ ReceiveVideoStreamIndexTask.ts:145
handleIndexFrame @ ReceiveVideoStreamIndexTask.ts:84
handleSignalingClientEvent @ ReceiveVideoStreamIndexTask.ts:56
sendEvent @ DefaultSignalingClient.ts:348
receiveMessage @ DefaultSignalingClient.ts:286
(anonymous) @ DefaultSignalingClient.ts:362
index.esm.js:7005 [MeetingManager audioVideoDidStart] Meeting started successfully
ConsoleLogger.ts:82 2022-02-11T10:36:11.229Z [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b was canceled due to subtask AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b/Timeout15000ms error: serial group task AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b/Timeout15000ms/UpdateSession/SetLocalDescriptionTask error: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='1'.
log @ ConsoleLogger.ts:82
warn @ ConsoleLogger.ts:40
handleMeetingSessionStatus @ DefaultAudioVideoController.ts:1298
(anonymous) @ DefaultAudioVideoController.ts:1073
perform @ DefaultSessionStateController.ts:86
(anonymous) @ DefaultAudioVideoController.ts:1066
rejected @ DefaultAudioVideoController.ts:3
Promise.then (async)
step @ DefaultAudioVideoController.ts:3
(anonymous) @ DefaultAudioVideoController.ts:3
push../node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter @ DefaultAudioVideoController.ts:3
actionUpdateWithRenegotiation @ DefaultAudioVideoController.ts:1042
(anonymous) @ DefaultAudioVideoController.ts:780
perform @ DefaultSessionStateController.ts:86
update @ DefaultAudioVideoController.ts:779
resubscribe @ ReceiveVideoStreamIndexTask.ts:145
handleIndexFrame @ ReceiveVideoStreamIndexTask.ts:84
handleSignalingClientEvent @ ReceiveVideoStreamIndexTask.ts:56
sendEvent @ DefaultSignalingClient.ts:348
receiveMessage @ DefaultSignalingClient.ts:286
(anonymous) @ DefaultSignalingClient.ts:362
ConsoleLogger.ts:82 2022-02-11T10:36:11.335Z [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b was canceled due to subtask AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b/Timeout15000ms error: serial group task AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/30263450-fbe2-4fca-8cd1-64f6210b2954/4c876cbc-8f9a-8ad2-2f4a-61091383fd6b/Timeout15000ms/UpdateSession/CreateSDPTask error: Failed to execute 'createOffer' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Failed to set local video description recv parameters for m-section with mid='1'..
log @ ConsoleLogger.ts:82
warn @ ConsoleLogger.ts:40
handleMeetingSessionStatus @ DefaultAudioVideoController.ts:1298
(anonymous) @ DefaultAudioVideoController.ts:1073
perform @ DefaultSessionStateController.ts:86
(anonymous) @ DefaultAudioVideoController.ts:1066
rejected @ DefaultAudioVideoController.ts:3
Promise.then (async)
step @ DefaultAudioVideoController.ts:3
(anonymous) @ DefaultAudioVideoController.ts:3
push../node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter @ DefaultAudioVideoController.ts:3
actionUpdateWithRenegotiation @ DefaultAudioVideoController.ts:1042
(anonymous) @ DefaultAudioVideoController.ts:780
perform @ DefaultSessionStateController.ts:86
update @ DefaultAudioVideoController.ts:779
resubscribe @ ReceiveVideoStreamIndexTask.ts:145
handleIndexFrame @ ReceiveVideoStreamIndexTask.ts:84
handleSignalingClientEvent @ ReceiveVideoStreamIndexTask.ts:56
sendEvent @ DefaultSignalingClient.ts:348
receiveMessage @ DefaultSignalingClient.ts:286
(anonymous) @ DefaultSignalingClient.ts:362
index.esm.js:7005 [MeetingManager audioVideoDidStart] Meeting started successfully
index.js:1 2022-02-11T10:36:13.916Z [ERROR] SDK - missing TURN credentials - falling back to fetch
console.<computed> @ index.js:1
log @ ConsoleLogger.ts:79
error @ ConsoleLogger.ts:44
(anonymous) @ ReceiveTURNCredentialsTask.ts:45
(anonymous) @ ReceiveTURNCredentialsTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/ReceiveTURNCredentialsTask.js.__awaiter @ ReceiveTURNCredentialsTask.ts:3
run @ ReceiveTURNCredentialsTask.ts:39
(anonymous) @ BaseTask.ts:63
(anonymous) @ BaseTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/BaseTask.js.__awaiter @ BaseTask.ts:3
baseRun @ BaseTask.ts:48
(anonymous) @ SerialGroupTask.ts:40
fulfilled @ SerialGroupTask.ts:3
Promise.then (async)
step @ SerialGroupTask.ts:3
fulfilled @ SerialGroupTask.ts:3
Promise.then (async)
step @ SerialGroupTask.ts:3
(anonymous) @ SerialGroupTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/SerialGroupTask.js.__awaiter @ SerialGroupTask.ts:3
run @ SerialGroupTask.ts:32
(anonymous) @ BaseTask.ts:63
(anonymous) @ BaseTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/BaseTask.js.__awaiter @ BaseTask.ts:3
baseRun @ BaseTask.ts:48
(anonymous) @ SerialGroupTask.ts:40
fulfilled @ SerialGroupTask.ts:3
Promise.then (async)
step @ SerialGroupTask.ts:3
(anonymous) @ SerialGroupTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/SerialGroupTask.js.__awaiter @ SerialGroupTask.ts:3
run @ SerialGroupTask.ts:32
(anonymous) @ BaseTask.ts:63
(anonymous) @ BaseTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/BaseTask.js.__awaiter @ BaseTask.ts:3
baseRun @ BaseTask.ts:48
(anonymous) @ TimeoutTask.ts:36
(anonymous) @ TimeoutTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/TimeoutTask.js.__awaiter @ TimeoutTask.ts:3
run @ TimeoutTask.ts:29
(anonymous) @ BaseTask.ts:63
(anonymous) @ BaseTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/BaseTask.js.__awaiter @ BaseTask.ts:3
baseRun @ BaseTask.ts:48
(anonymous) @ SerialGroupTask.ts:40
(anonymous) @ SerialGroupTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/SerialGroupTask.js.__awaiter @ SerialGroupTask.ts:3
run @ SerialGroupTask.ts:32
(anonymous) @ BaseTask.ts:63
(anonymous) @ BaseTask.ts:3
push../node_modules/amazon-chime-sdk-js/build/task/BaseTask.js.__awaiter @ BaseTask.ts:3
baseRun @ BaseTask.ts:48
(anonymous) @ DefaultAudioVideoController.ts:1188
(anonymous) @ DefaultAudioVideoController.ts:3
push../node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter @ DefaultAudioVideoController.ts:3
actionReconnect @ DefaultAudioVideoController.ts:1162
(anonymous) @ DefaultAudioVideoController.ts:1144
perform @ DefaultSessionStateController.ts:86
performDeferredAction @ DefaultSessionStateController.ts:164
perform @ DefaultSessionStateController.ts:97
(anonymous) @ DefaultAudioVideoController.ts:1203
fulfilled @ DefaultAudioVideoController.ts:3
Promise.then (async)
step @ DefaultAudioVideoController.ts:3
(anonymous) @ DefaultAudioVideoController.ts:3
push../node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter @ DefaultAudioVideoController.ts:3
actionReconnect @ DefaultAudioVideoController.ts:1162
(anonymous) @ DefaultAudioVideoController.ts:1144
perform @ DefaultSessionStateController.ts:86
(anonymous) @ DefaultAudioVideoController.ts:1143
(anonymous) @ DefaultAudioVideoController.ts:3
push../node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter @ DefaultAudioVideoController.ts:3
(anonymous) @ DefaultAudioVideoController.ts:1136
(anonymous) @ DefaultReconnectController.ts:89
(anonymous) @ TimeoutScheduler.ts:18
setTimeout (async)
start @ TimeoutScheduler.ts:16
retryWithBackoff @ DefaultReconnectController.ts:87
reconnect @ DefaultAudioVideoController.ts:1136
handleMeetingSessionStatus @ DefaultAudioVideoController.ts:1296
(anonymous) @ DefaultAudioVideoController.ts:1073
perform @ DefaultSessionStateController.ts:86
(anonymous) @ DefaultAudioVideoController.ts:1066
rejected @ DefaultAudioVideoController.ts:3
Promise.then (async)
step @ DefaultAudioVideoController.ts:3
(anonymous) @ DefaultAudioVideoController.ts:3
push../node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.js.__awaiter @ DefaultAudioVideoController.ts:3
actionUpdateWithRenegotiation @ DefaultAudioVideoController.ts:1042
(anonymous) @ DefaultAudioVideoController.ts:780
perform @ DefaultSessionStateController.ts:86
update @ DefaultAudioVideoController.ts:779
resubscribe @ ReceiveVideoStreamIndexTask.ts:145
handleIndexFrame @ ReceiveVideoStreamIndexTask.ts:84
handleSignalingClientEvent @ ReceiveVideoStreamIndexTask.ts:56
sendEvent @ DefaultSignalingClient.ts:348
receiveMessage @ DefaultSignalingClient.ts:286
(anonymous) @ DefaultSignalingClient.ts:362
Show 29 more frames
Video:1 Access to fetch at 'https://2954.cell.ap-southeast-1.meetings.chime.aws/v2/turn_sessions?X-Amzn-Version=2.23.0&X-Amzn-User-Agent=chrome-90' from origin 'http://localhost:3001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
ReceiveTURNCredentialsTask.ts:75          POST https://2954.cell.ap-southeast-1.meetings.chime.aws/v2/turn_sessions?X-Amzn-Version=2.23.0&X-Amzn-User-Agent=chrome-90 net::ERR_FAILED
