### ISSUE TITLE
Roster Attendee icons don't change color when darkTheme used

### ISSUE THREAD

**Issue by aneeshj4** [aws/amazon-chime-sdk-component-library-react#846] opened 2022-10-26 14:04 UTC
### What happened and what did you expect to happen?

At the root level of our application we have added the ThemeProvider to enable the dark theme. The UI is updating accordingly except for the icons in the RosterCell component (which we are indirectly using via the RosterAttendee component). As shown in the image below, the theme is the dark theme except for the icons which are still following the light theme.

<img width="297" alt="Roster Attendee incorrect icon color" src="https://user-images.githubusercontent.com/16766587/198043928-f4c0307b-3e63-4bbb-ad16-67deda252666.png">

We have added the theme into the component as follows.

`
<ThemeProvider theme={isDarkMode ? darkTheme : lightTheme}>
        <BackgroundBlurProvider>
	        <MeetingProvider>
	            <CallScreen />
	        </MeetingProvider>
        </BackgroundBlurProvider>
  </ThemeProvider>
`

I also tested adding the ThemeProvider directly above the RosterAttendee component and it did not fix it.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

Apply dark theme to the UI and observe the icons in the RosterAttendee component.

### Amazon Chime SDK React Components Library version

3.3.0 (this is the most up to date version in npm, even though the repository says 3.4.0)

### What browsers are you seeing the problem on?

Chrome, Safari

### Browser version

Chrome 106, Safari 15.4

### Device Information

Desktop

### Browser console logs

N/A

**Comment by xuesichao** [comment] 2022-10-26 22:37
@aneeshj4 Hi, I was not able to reproduce this issue using our [meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting). After comparing the code, I think the cause for this issue is that you didn't add `<GlobalStyles />` under `<ThemeProvider>`. Could you give it a try?
Example: https://github.com/aws-samples/amazon-chime-sdk/blob/2c7a7c2b446981ae682976d4c29cf036cd73e738/apps/meeting/src/app.tsx#L42

**Comment by aneeshj4** [comment] 2022-10-26 23:41
@xuesichao that fixed it, thank you!! I didn't see GlobalStyles mentioned anywhere in the [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/themes--page), is it something specific to this use case or should it always be included?

**Comment by xuesichao** [comment] 2022-10-27 17:24
@aneeshj4 Yes, we use this `<GlobalStyles >` to do global CSS reset. Not sure why it's missing in our documentation but I'll update our documentation to recommend using it along with `<ThemeProvider />`.

**Comment by devalevenkatesh** [comment] 2022-11-02 19:57
The documentation update PR is merged, thank you for your patience. Resolving this issue now.

**Closed by devalevenkatesh** 2022-11-02 19:57 UTC
Labels: Documentation
