### ISSUE TITLE
Can't detect the presence if User joins meeting with Camera & Mic Blocked in Safari

### ISSUE THREAD

**Issue by arpitmittal-lab** [aws/amazon-chime-sdk-component-library-react#705] opened 2021-12-29 10:53 UTC
### What happened and what did you expect to happen?

- Open Safari 
- Block Camera & Mic Permission 
- Join Meeting with blocked camera & permission deny all the permissions
- User is able to join the meeting as a ghost and the other members in meeting won't notice him.

Verified on: https://g7ih460j8l.execute-api.us-east-1.amazonaws.com/Prod/

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

- Open Safari 
- Block Camera & Mic Permission 
- Join Meeting with blocked camera & permission deny all the permissions
- User is able to join the meeting as a ghost and the other members in meeting won't notice him.

### Amazon Chime SDK React Components Library version

2.12.0

### What browsers are you seeing the problem on?

Safari

### Browser version

Any

### Device Information

MAC (Desktop / Mobile)

### Browser console logs

Not required.

**Comment by xuesichao** [comment] 2021-12-29 18:42
Hi @arpitmittal-lab , Amazon Chime SDK for JavaScript use audio signal to detect whether or not an attendee has joined the meeting. Safari browser's Auto Play policy will block the audio signal if user blocks the permission.

One solution is to "Allow All Auto-play" for your project URL in Safari Preference.
Check the details here: https://github.com/aws/amazon-chime-sdk-js/issues/474#issuecomment-870861009

Close the issue as a duplicate of https://github.com/aws/amazon-chime-sdk-js/issues/474

**Closed by xuesichao** 2021-12-29 18:42 UTC
