### ISSUE TITLE
Preview Video not loading on v2.12.0

### ISSUE THREAD

**Issue by jherrera-bcov** [aws/amazon-chime-sdk-component-library-react#708] opened 2022-01-05 17:20 UTC
### What happened and what did you expect to happen?

**Problem**
PreviewVideo component is used in a device selection screen. After updating to `v2.12.0` the video does not load. 
No other instances of video are present, only the preview.

Issue is solved by changing camera device or by turning the background blur on/off.

**Expected result**
PreviewVideo should load the video for users

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting#readme---react-meeting-demo)

### Reproduction steps

1. Use PreviewVideo 
3. Accept browser permissions 
2. Video element is rendered but no video is shown

### Amazon Chime SDK React Components Library version

2.12.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 96.0.4664.110

### Device Information

Desktop: Mac OS 10.15.7

### Meeting and Attendee ID Information.

Meeting ID: preview_issue_05_jan
Attendee ID: 17e82749-f0b0-bd61-1a32-60b9733027b1

### Browser console logs

None

### Add any other context about the problem here.

The issue is only present before `meetingManager.start()` is called. It was present on mobile and desktop browsers
I know the `PreviewVideo` component received some updates, could it be that we need to change something?

**Comment by michhyun1** [comment] 2022-01-05 23:20
@jherrera-bcov Can you please give more details on how you're using the PreviewVideo component? 

You need to first choose a device before it can display any video:

``` await meetingManager.selectVideoInputDevice(DEVICE_ID) ```

Have you done this?

**Comment by jherrera-bcov** [comment] 2022-01-06 14:27
We use the `CameraSelection` and `QualitySelection` components to modify the device. As I understand `CameraSelection` selects the first option available.
Moreover, we ask for browser permissions before displaying the device selection and camera preview. 
This issue appeared when upgrading to `2.12.0`, could it be that we have to modify the code to accommodate the PreviewVideo changes?

**Comment by michhyun1** [comment] 2022-01-06 21:25
@jherrera-bcov  How are you asking for browser permissions?

**Comment by jherrera-bcov** [comment] 2022-01-07 14:42
We use to track user permissions. Once the status  `useDevicePermissionStatus()` is Granted we allow users to preview video. 
Users join the meeting before previewing the video, but it is started after they reach the Device Selection screen.

**Comment by michhyun1** [comment] 2022-01-07 21:17
@jherrera-bcov  Could you please send me some browser logs? 

When you call `meetingManager.join`, it should `listAndSelect` the default video device for you, and the PreviewVideo component should be showing that default device stream when its mounted.

**Comment by michhyun1** [comment] 2022-01-14 01:01
@jherrera-bcov any update?

**Comment by jherrera-bcov** [comment] 2022-01-14 17:06
@michhyun1 we are in the process of adding Chime Logger to the application. At the moment I cannot provide the required logs

**Comment by michhyun1** [comment] 2022-01-14 22:23
@jherrera-bcov let me know if you have logs - the preview video component should initialize with the `meetingManager.selectedVideoTransformDevice.` 
That property is set when you intialize a meeting session, or join a meeting.

**Comment by brynrichards** [comment] 2022-02-04 20:21
@michhyun1 We have encountered the same problem after upgrading, no preview video is shown on our device setup page until the default video device is changed or toggle on and off.

I've tracked down the cause by cloning the PreviewVideo component.   audioVideo is null when startPreview is called here (device is not null):

https://github.com/aws/amazon-chime-sdk-component-library-react/blob/61464e15175b0f88d141f968790524c5443ea5d1/src/components/sdk/PreviewVideo/index.tsx#L57

So the preview doesn't start.  The audioVideo is set after the device is set.  

Fixed by adding audioVideo to the dependency array here:

https://github.com/aws/amazon-chime-sdk-component-library-react/blob/61464e15175b0f88d141f968790524c5443ea5d1/src/components/sdk/PreviewVideo/index.tsx#L67

**Comment by ltrung** [comment] 2022-02-04 22:56
@jherrera-bcov The fix PR #737 (Thank @brynrichards) has been merged to main. Could you verify that it fixes it on your end?

**Comment by brynrichards** [comment] 2022-02-05 09:09
@ltrung @michhyun1 fyi - tested 2.15 here (and backing out to 2.14 to confirm the issue re-appears, and then back to 2.15) and can confirm it has fixed the issue we were seeing. thanks for the quick turnaround!

**Comment by jherrera-bcov** [comment] 2022-02-08 16:40
@ltrung Tested with `2.15`, issue has been fixed. Thanks!

**Closed** 2022-02-08 17:16 UTC
Labels: Bug, device
