### ISSUE TITLE
adding name to the attendee roster 

### ISSUE THREAD

**Issue by TGod-Ajayi** [aws/amazon-chime-sdk-component-library-react#239] opened 2020-10-13 06:41 UTC
**Describe the bug**
in the documentation  https://aws.github.io/?path=/docs/introduction--page
it says you can add name to the attendee  like this 

import { useMeetingManager } from 'amazon-chime-sdk-component-library-react';

const MyApp = () => {
  const meetingManager = useMeetingManager();

  useEffect(() => {
    meetingManager.getAttendee = async (chimeAttendeeId: string, externalUserId?: string) => {
      const response = await fetch('/my-attendees-endpoint);
      const user = await response.json();

      return {
        name: user.name
      }
    }
  }, [])
}

problem is how do we call the .getAttendee and pass the chimeId & externalUserId 
when you try this meetingManager.getAttendee() or this  meetingManager.getAttendee(function getAndReturnName(id,externald)) you get a .getAttendee is not. a function
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by p-foucht** [comment] 2020-10-13 17:41
Hi @TGod-Ajayi

`meetingManager.getAttendee` gets called when users join the meeting session. The general flow is 

- Provide meetingManger a valid getAttendee callback
- Attendee joins the meeting session (assuming you've started the meeting at this point). MeetingManager then calls your provided callback, and expects an object with a name to be returned
- The roster state is updated, which you can access using the `useRosterState` hook [(found here)](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-hooks-userosterstate--page)

**Comment by TGod-Ajayi** [comment] 2020-10-13 17:53
hello @p-foucht  so let me get this straight 
I want to start a meeting 
I have this 
`useEffect(() => {
     // call api to get the meeting details
       const joinData = {
      meetingInfo:meetingInfo,
      attendeeInfo:attendeeInfo
    };
       meetingManager.join(joinData);
       meetingManager.start();
      // meeting started 

},[])`
that is the code generally how I am starting my meeting
how do I call this `meetingManager.getAttendee` and from what i saw in the docs we have to pass 
`chimeAttendeeId: string, externalUserId?: string`
how do I pass these values

**Comment by TGod-Ajayi** [comment] 2020-10-13 18:03
@p-foucht  I am trying to achieve video nameplates from the code I can see the featuredVideo already has the code to get the attendee from the roster and display the name if available my problem now is just adding the name to the rooster when the user joins the meeting.... when do I do this? do I call the **meetingManager.getAttendee** after user has joined if yes like you wrote how do I call it and pass the chimeAttendeeId, externalUserId

**Comment by p-foucht** [comment] 2020-10-13 21:22
The meetingManager will call the function you provide for `meetingManager.getAttendee`, you should not call this method explicitly

```
meetingManager.getAttendee = async (chimeAttendeeId: string, externalUserId?: string) => { 
  console.log("An attendee joined session");
  //  Fetch attendee info from my own server, and return it here
}
```

When an attendee join the meeting session, meetingManager calls the callback with the chimeAttendeeId and the externalUserId (if applicable). The function then needs to fetch the data and return it, which will then be included in the rosterState

Here is what the repo demo does
- [Assign a callback](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/f9aa107f3ee11d5069380671c4be9df1ffd50881/demo/meeting/src/containers/MeetingForm/index.tsx#L62) to getAttendees. This function takes in the [chime and external ID](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/demo/meeting/src/utils/api.ts#L40), fetches some data, and returns the name. The `useRosterState` should now include the name property for each attendee

**Comment by TGod-Ajayi** [comment] 2020-10-14 03:56
Ok I did like in the demo and noticed couple of things 

1. in my application the names get interchanged 
for example for say my call back returns James for chimeId === B
and susan for chime Id -=== A
in the video name plates 
when ChimeId B turn on camera
in Chime Id A viewing area the name comes up Susan vice-versa
so in the name plates when susan in susan side she sees her name comes up in James video same with James 

2. The Rooster doesnt get updated... when we console.log() I see the name of the first person to join reapted in the second persons rooster object

**Comment by p-foucht** [comment] 2020-10-14 13:49
Do the external IDs look correct for each user when your `getAttendee` function is firing?

The provider just calls your `getAttendee` function [with the IDs and assigns whatever you return](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/providers/RosterProvider/index.tsx#L62-L71) to that attendee object in the roster. 

Is this something you can reproduce in the demo repo?

**Comment by p-foucht** [comment] 2020-10-19 15:40
Resolving this since there hasn't been any activity after the last response. Feel free to re-open if necessary

**Closed by p-foucht** 2020-10-19 15:40 UTC
Labels: Bug
