### ISSUE TITLE
toggleVideo takes two attempts to switch on local tile

### ISSUE THREAD

**Issue by k-ahn** [aws/amazon-chime-sdk-component-library-react#391] opened 2021-01-21 23:31 UTC
I am using the exact block of code in Section 3 [here](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/introduction--page) to successfully start a meeting and converse using audio. 

My issue is with starting my local video - i have to toggle on, off, then on again for it to render the local tile. I am using the code as stated in the documentation [here](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/docs/sdk-components-localvideo--page)

```
const { toggleVideo } = useLocalVideo();
<button onClick={toggleVideo}>Toggle video</button>
```

**To Reproduce**
1. Start the meeting
2. Click Toggle video (On)
3. Video on for remote attendees but no local tile appears
4. Click Toggle video (Off)
5. Video goes off for remote attendees
6. Click Toggle video (On)
7. Video on for remote attendees AND local tile appears

**Expected behavior**
Local tile should appear when video is first switched on.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.96

**Additional context**
I also tested with 3 attendees. In this scenario to grid expanded but no video tile appeared until the second attempt.

**Comment by nicklera1** [comment] 2021-01-22 21:41
Thanks @k-ahn. 
I will be trying to replicate your issue with minimalistic app just like you described but meanwhile 
Have you tried our demo application within ```demo/meeting``` folder?  as I'm not able to replicate issue and so would like to see if you could try the same. 

I will update once tryout with your steps!
Thanks

**Comment by JannikSt** [comment] 2021-01-25 12:33
+1

**Comment by ahmet-tas** [comment] 2021-01-25 12:46
Exact same issue. LocalTile must be turned off and on again, to view myself. Pretty annoying, because I'm not aware that my video is already being streamed to others....

**Comment by k-ahn** [comment] 2021-01-25 15:22
> Thanks @k-ahn.
> I will be trying to replicate your issue with minimalistic app just like you described but meanwhile
> Have you tried our demo application within `demo/meeting` folder? as I'm not able to replicate issue and so would like to see if you could try the same.
> 
> I will update once tryout with your steps!
> Thanks

I will try this and feedback to assist with debugging, though the responses are highlighting a common problem.

**Comment by p-foucht** [comment] 2021-01-26 22:25
Hey all, thanks for bringing this up. A few questions to try and troubleshoot this

- What version of the JS SDK are you all on? Is it reproducible on the latest version of the JS SDK/Compnents?
- Is the `LocalVideo` rendered conditionally or anything? For example, `{ isVideoEnabled ? <LocalVIdeo /> : null }`. Any details around how your application renders the meeting UI would be helpful
- How often are you able to reproduce?
- Do you see the same issue when trying out the repo demo?

I haven't been able to reproduce it using the demo yet so looking for a bit more detail

**Comment by henlamk** [comment] 2021-01-27 08:18
What version of the JS SDK are you all on? Is it reproducible on the latest version of the JS SDK/Compnents?
I have tried versions from 1.4 to 1.6. 

    Is the LocalVideo rendered conditionally or anything? For example, { isVideoEnabled ? <LocalVIdeo /> : null }. Any details around how your application renders the meeting UI would be helpful
No. 

    How often are you able to reproduce?
Every time after joining a meeting. 

    Do you see the same issue when trying out the repo demo?
No. 

I have found a workaround that we will most likely use until this issue is resolved properly. 
`         audioVideo?.startLocalVideoTile()
         setTimeout(toggleVideo, 300)`
Hope you can draw something out of this.

**Comment by p-foucht** [comment] 2021-01-27 16:26
Thank you for the additional details @henlamk. Just a few more questions if you don't mind

- I'm assuming version 1.4-1.6 you mean for components, what version of the SDK are you on? 
- Would it be possible to share the `info` level SDK logs of the meeting session?
- Are you using the `VideoTileGrid`, or are you creating your own grid and using `LocalVideo` directly?

**Comment by k-ahn** [comment] 2021-01-27 21:13
My responses are:

_What version of the JS SDK are you all on? Is it reproducible on the latest version of the JS SDK/Compnents?_
"amazon-chime-sdk-component-library-react": "^1.6.0",
"amazon-chime-sdk-js": "^1.20.2",

_Is the LocalVideo rendered conditionally or anything? For example, { isVideoEnabled ? <LocalVIdeo /> : null }. Any details around how your application renders the meeting UI would be helpful_
No - just `<LocalVideo />` within Return() and some surrounding HTML

_How often are you able to reproduce?_
Every time

_Do you see the same issue when trying out the repo demo?_
I've not tested this yet - i will do so but i assume the same answer as @henlamk 

_Are you using the VideoTileGrid, or are you creating your own grid and using LocalVideo directly?_
I am using `VideoTileGrid` and i've tested with and without `LocalVideo` - no different. 

_Would it be possible to share the info level SDK logs of the meeting session?_

Attached is my INFO output from the console. The key event start times are:
- Meeting start: 20:54:27.961
- Toggle Video ON: 20:54:37.814 <-- Nothing displayed
- Toggle Video OFF: 20:54:48.044
- Toggle Video ON: 20:54:57.959 <-- Local video appeared

[console_output.txt](https://github.com/aws/amazon-chime-sdk-component-library-react/files/5883030/console_output.txt)

**Comment by k-ahn** [comment] 2021-01-27 22:41
Update:
- I tested the demo App, issue was not reproduced (consistent with @henlamk)
- I noticed the demo App was using `amazon-chime-sdk-js": "^2.4.x`. I've now upgraded but it has made no difference - the issue persists

**Comment by p-foucht** [comment] 2021-02-01 20:14
Appreciate all the details you both have provided. Unfortunately I still haven't been able to repro, so I'm wondering what might be the difference between the demo app and both of your applications

If you could provide a general structure of your app, and mabe some details around the user flow (from joining a meeting to starting their local video), it would really help me find a way to repro this issue

I am curious about the workaround @henlamk provided. Do you get any SDK logs around local video is already playing?

**Comment by k-ahn** [comment] 2021-02-01 23:00
Hi @p-foucht 

I am able to reproduce this issue with a clean react build and the aforementioned code. I'll explain what i did:

1. `npm create-react-app aws-react-test-391`
2. `cd aws-react-test-391`
3. `npm install amazon-chime-sdk-js amazon-chime-sdk-component-library-react styled-components styled-system`
4. Overwrite `index.js` and `App.js` with the versions attached (changing the .txt extension to .js). You'll see that `index.js` has the `MeetingProvider` and `ThemeProvider `wrapper and `App.js` is updated with the `joinMeeting` function from the instructions and minimal HTML
5. I then pasted the JSON for the `meeting` and `attendee` into the code. You can replace this with an API call if you prefer, I used my operational app and the command line to get the data.
6. Run `npm start`
7. Click the **join** button
8. Next click **ToggleVideo** and the defect is reproducible - you need to press it three times **ON** - **OFF** - **ON**.

The only other thing i had to do was set chrome://flags/#unsafely-treat-insecure-origin-as-secure to allow HTTP to work. This is required to allow device access when using HTTP and localhost and has nothing to do with the defect, which is the same over HTTPS.

Thanks in advance - i really need to get this fixed and live.

[App.txt](https://github.com/aws/amazon-chime-sdk-component-library-react/files/5907327/App.txt)
[index.txt](https://github.com/aws/amazon-chime-sdk-component-library-react/files/5907328/index.txt)

**Comment by p-foucht** [comment] 2021-02-02 18:30
Thank you for the in-depth steps! I'll give this a try now and hopefully reproduce it

**Comment by p-foucht** [comment] 2021-02-02 19:53
Just to update -- I'm able to reproduce the issue with the steps provided. Looking into a root cause/fix now

**Comment by kh09211** [comment] 2021-02-05 04:36
Hello, I am having this same issue. When set to a button, In many cases I must click toggleVideo() 4+ times before the video appears in the VideoTileGrid. This is troublesome because my use case is that I want to start the video when the user closes a modal, however once the modal closes even though toggleVideo() is in the function, it does not add the users video to the grid. Looking at another issue on github, I found that I can render the video immediately with a:

```
useEffect(() => {
		// don't toggle video until the audioVideo instance is available on the page
		if (audioVideo) {
			console.log('audioVideo true');
			toggleVideo();
		}
	}, [audioVideo])
```

however this renders the user's video immediately on load. If I try to change cameras or if I add any other variable in the useEffect array such as !showModal, it just doesnt work.

I have spent 2 days trying to make this work. Hopefully there will be a fix soon or a workaround to the button issue. Thanks.

**Comment by k-ahn** [comment] 2021-02-05 08:35
@p-foucht Great to see the issue reproduced and Pull Request #405 in progress. May i ask - what are the likely timings for fix availability? Thanks

**Comment by p-foucht** [comment] 2021-02-05 18:42
We are in process of releasing v2.0 early next week, which is preventing merging it in. After the 2.0 release, we'll go ahead and get this in and release it as a patch/minor update

**Comment by p-foucht** [comment] 2021-02-12 16:26
This was released yesterday in  `amazon-chime-sdk-component-library-react@2.0.1` 

I've verified that the steps provided by @k-ahn no longer reproduce the issue. Resolving this, but please reopen if you continue to experience this issue.

**Closed by p-foucht** 2021-02-12 16:26 UTC
Labels: Bug, Needs More Information, Triaged
