### ISSUE TITLE
No audio output in chrome 92 version with react-frame-component

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-component-library-react#579] opened 2021-07-27 15:10 UTC
### What happened and what did you expect to happen?

When wrapping MeetingProvider with react-frame-component, there's no audio output for attendee on chrome after latest chrome update to **92.0.4515.107**. It's working fine in older versions. The issue is reproducible on meeting demo as well. Although Test speaker on Device Selection screen works fine in all versions.

Observations - 
- isAudioOn from useLocalAudioOutput() is true.
-  AttendeeAudioStatus for other attendees in meeting signalStrength: 1, muted: false.

### Have you reviewed our existing documentation?

- [X] Amazon Chime SDK for JavaScript GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] Amazon Chime SDK React Components Library GitHub [issues](https://github.com/aws/amazon-chime-sdk-component-library-react/issues)
- [X] Storybook [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-component-library-react#readme)
- [X] How-to [documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/how-tos--page)
- [X] React SDK meeting [demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting#readme---react-meeting-demo)

### Reproduction steps

In meeting demo, app.tsx - https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/meeting/src/app.tsx
`import Iframe from 'react-frame-component';`  (version - ^4.0.2)
And wrap MeetingProvider on line 39 with Iframe.
It's working fine on safari (macOS,iOS) and chrome - version 91.0.4472.164 but stopped working for chrome version 92.

### Amazon Chime SDK React Components Library version

2.7.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 92.0.4515.107 

### Device Information

MacOS, Windows, Android

### Meeting and Attendee ID Information.

 MeetingId: "c21f1031-ffa0-4660-b80a-57a8b9b40706"

AttendeeId for problematic Attendee (on chrome): "64e4db44-cb23-48c4-0c91-cec6c32e89d9"
Other AttendeeId (on safari): "b03aa860-73e3-2b35-1344-3e73da78ab14"

### Browser console logs

[AttendeeOnChrome.log](https://github.com/aws/amazon-chime-sdk-component-library-react/files/6886569/AttendeeOnChrome.log)

**Comment by anuranduttaroy** [comment] 2021-07-29 00:41
Hey @shriyajuneja 

Thanks for reporting this issue. I tried to wrap the meeting manager inside an `IFrame` and tried to join a meeting from `Firefox  v90.0.2`, `Safari Version 14.1.2` &  `Chrome Version 92.0.4515.107` and was able to reproduce it. 

Here are the observations
1. Speaking from Firefox -> Able to hear from Safari but NOT from Chrome
2. Speaking from Safari -> Able to hear from Firefox but NOT from Chrome
3. Speaking from Chrome -> Able to hear in Firefox & Safari

Issue: Not able to hear audio when meeting manager is wrapped in `Chrome Version 92`.

Looking into why this is happening.

**Comment by anuranduttaroy** [comment] 2021-08-05 00:13
Tried running a sample react app in my localhost with an `Iframe` embedded into it. 

**Observations**
1. Using normal `<iframe>` (Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe)
    - I am able to load both the [React Components meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) and the [JS SDK Serverless Meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser)
    - I am able to hear audio from all the participants.
 2. Using the `<Iframe>` from `react-frame-component` (Ref: https://www.npmjs.com/package/react-frame-component) 
    - I am only able to load the JS SDK Serverless Meeting demo in all the browsers. I am not able to load the React Components meeting demo in Chrome 92. Firefox is able to load.
    - I am not able to hear audio from any `<Iframe>` users.


With all this testing, it looks like an issue with the `<Iframe>` from `react-frame-component` i.e https://www.npmjs.com/package/react-frame-component


**Next actions**: Can you try out these scenarios with regular `<iframe>` (Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) and see if the issue occurs. 


-------
Here is my sample code that I used to run the code locally

```
import logo from './logo.svg';
import './App.css';
import Iframe from 'react-frame-component';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        <Iframe allow="camera;microphone" title="test" src="<demo-app-url-i-was-testing>" width="1500px" height="1500px"></Iframe>
      </header>
    </div>
  );
}

export default App;
```

**Comment by shriyajuneja** [comment] 2021-08-05 16:28
Hi @anuranduttaroy , I tried running meet using normal <iframe> (Ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe), it worked for all browsers.

I'm able to load react-component meeting demo in Chrome 92 using [react-frame-component](https://www.npmjs.com/package/react-frame-component), other participants can hear chrome user(using react-frame-component), but user on chrome 92 is unable to hear other participants.
> * I am only able to load the JS SDK Serverless Meeting demo in all the browsers. I am not able to load the React Components meeting demo in Chrome 92. Firefox is able to load.

**Comment by devalevenkatesh** [comment] 2021-08-13 01:51
Hello @shriyajuneja ,

Since normal <iframe> is working with both of the JS SDK and React SDK demos, so could you please check with the custom `react-frame-component` library for any issues?

**Comment by devalevenkatesh** [comment] 2021-10-04 23:41
Closing this issue as no further action can be taken. Feel free to re-open or create a new issue.

**Closed by devalevenkatesh** 2021-10-04 23:41 UTC
Labels: Question
