### ISSUE TITLE
[FEATURE REQUEST] Mute all others attendee for host

### ISSUE THREAD

**Issue by BananaGarden** [aws/amazon-chime-sdk-component-library-react#640] opened 2021-10-06 06:44 UTC
Hi,

Can and how we have a control to mute all others attendee for host (organizer)?

Thanks!

**Comment by vidya-mohan** [comment] 2022-02-23 22:20
Marking as duplicate of https://github.com/aws/amazon-chime-sdk-js/issues/237

**Closed as completed by vidya-mohan** 2022-02-23 22:20 UTC
Labels: feature-request
